"use client";
import {useEffect,useState} from 'react';
import {onAuthStateChanged,signInWithEmailAndPassword,createUserWithEmailAndPassword,sendEmailVerification,sendPasswordResetEmail,signOut,User} from 'firebase/auth';
import {auth,configured} from '../lib/firebase-client';
import Garage from './garage';
export default function AuthGate(){const [user,setUser]=useState<User|null>(null),[ready,setReady]=useState(!configured),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[register,setRegister]=useState(false);
useEffect(()=>{if(configured)return onAuthStateChanged(auth(),u=>{setUser(u);setReady(true);});},[]);
async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage('');try{if(register){const r=await createUserWithEmailAndPassword(auth(),email,password);await sendEmailVerification(r.user);setMessage('Te hemos enviado un correo para verificar tu cuenta.');}else await signInWithEmailAndPassword(auth(),email,password);}catch{setMessage('No se ha podido entrar. Revisa el correo y la contraseña. Si ya tienes cuenta, prueba recuperar la contraseña.');}finally{setBusy(false);}}
if(!ready)return <main className="login"><p>Cargando…</p></main>;
if(user?.emailVerified)return <Garage/>;
return <main className="login"><img src="/hinata-driver-bn.png" width="110" height="110" alt="Hinata conduciendo"/><h1>Hinata Garaje</h1><p>El garaje de la familia.</p>{!configured?<div className="info-box">La app está preparada. Falta conectar el nuevo proyecto de Firebase siguiendo el archivo README.</div>:user?<><p>Verifica tu correo antes de entrar.</p><button className="primary" onClick={async()=>{await user.reload();await user.getIdToken(true);setUser(auth().currentUser);if(user.emailVerified)location.reload();}}>Ya he verificado mi correo</button><button className="secondary" onClick={async()=>{try{await sendEmailVerification(user);setMessage('Correo de verificación enviado.');}catch{setMessage('Espera unos minutos antes de volver a enviarlo.');}}}>Reenviar correo</button><button className="text-button" onClick={()=>signOut(auth())}>Cerrar sesión</button></>:<form onSubmit={submit}><label>Correo<input type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Contraseña<input type="password" minLength={6} autoComplete={register?'new-password':'current-password'} required value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="primary" disabled={busy}>{busy?'Espera…':register?'Crear cuenta':'Entrar'}</button><button type="button" className="text-button" onClick={()=>setRegister(!register)}>{register?'Ya tengo cuenta':'Crear mi cuenta'}</button><button type="button" className="text-button" onClick={async()=>{try{await sendPasswordResetEmail(auth(),email);setMessage('Si existe una cuenta con ese correo, recibirás instrucciones.');}catch{setMessage('Introduce un correo válido.');}}}>Recuperar contraseña</button></form>}{message&&<p role="status">{message}</p>}<small>Solo los cuatro correos autorizados pueden acceder a las reservas.</small></main>;
}
