"use client";
import {useEffect,useState} from 'react';
import {onAuthStateChanged,signInWithEmailAndPassword,createUserWithEmailAndPassword,sendEmailVerification,sendPasswordResetEmail,signOut,User} from 'firebase/auth';
import {auth,configured} from '../lib/firebase-client';
import Garage from './garage';
export default function AuthGate(){const [user,setUser]=useState<User|null>(null),[ready,setReady]=useState(!configured),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[register,setRegister]=useState(false);
useEffect(()=>{if(configured)return onAuthStateChanged(auth(),u=>{setUser(u);setReady(true);});},[]);
async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage('');try{if(register){const r=await createUserWithEmailAndPassword(auth(),email,password);await sendEmailVerification(r.user);setMessage('T’hem enviat un correu per verificar el compte.');}else await signInWithEmailAndPassword(auth(),email,password);}catch{setMessage('No s’ha pogut entrar. Revisa el correu i la contrasenya. Si ja tens compte, prova de recuperar la contrasenya.');}finally{setBusy(false);}}
if(!ready)return <main className="login"><p>Carregant…</p></main>;
if(user?.emailVerified)return <Garage/>;
return <main className="login"><img src="/hinata-driver-bn.png" width="110" height="110" alt="Hinata conduint"/><h1>Hinata Garatge</h1><p>El garatge de la família.</p>{!configured?<div className="info-box">L’app està preparada. Falta configurar la connexió amb Firebase seguint el fitxer README.</div>:user?<><p>Verifica el correu abans d’entrar.</p><button className="primary" onClick={async()=>{await user.reload();await user.getIdToken(true);setUser(auth().currentUser);if(user.emailVerified)location.reload();}}>Ja he verificat el correu</button><button className="secondary" onClick={async()=>{try{await sendEmailVerification(user);setMessage('Correu de verificació enviat.');}catch{setMessage('Espera uns minuts abans de tornar-lo a enviar.');}}}>Tornar a enviar el correu</button><button className="text-button" onClick={()=>signOut(auth())}>Tancar la sessió</button></>:<form onSubmit={submit}><label>Correu<input type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Contrasenya<input type="password" minLength={6} autoComplete={register?'new-password':'current-password'} required value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="primary" disabled={busy}>{busy?'Espera…':register?'Crear un compte':'Entrar'}</button><button type="button" className="text-button" onClick={()=>setRegister(!register)}>{register?'Ja tinc compte':'Crear el meu compte'}</button><button type="button" className="text-button" onClick={async()=>{try{await sendPasswordResetEmail(auth(),email);setMessage('Si hi ha un compte amb aquest correu, rebràs les instruccions.');}catch{setMessage('Introdueix un correu vàlid.');}}}>Recuperar la contrasenya</button></form>}{message&&<p role="status">{message}</p>}<small>Només els quatre correus autoritzats poden accedir a les reserves.</small></main>;
}
