'use client';
import {authenticatedFetch,download,auth} from '../lib/firebase-client';
import {signOut} from 'firebase/auth';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Car,CalendarDays,Plus,Users,Clock,ShieldCheck,Bell,X,Check,Download,RefreshCw,LogOut,TriangleAlert,History,CalendarPlus,Pencil,Trash2,WifiOff} from 'lucide-react';
import {Member,Reservation,violations,overlaps} from '../lib/rules';
type Event={id:string;reservation:string;actor:string;action:string;at:number;payload:any};
type State={me:Member;members:Member[];reservations:Reservation[];events:Event[];serverTime:number};
const ZONE='Europe/Madrid';
const date=(n:number,opts:Intl.DateTimeFormatOptions={})=>new Intl.DateTimeFormat('es-ES',{timeZone:ZONE,...opts}).format(n);
const time=(n:number)=>date(n,{hour:'2-digit',minute:'2-digit'});
const dayKey=(n:number)=>date(n,{year:'numeric',month:'2-digit',day:'2-digit'}).split('/').reverse().join('-');
function localInput(n:number){const parts=new Intl.DateTimeFormat('sv-SE',{timeZone:ZONE,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(n);return parts.replace(' ','T');}
function fromInput(s:string){const target=Date.parse(s+'Z');if(!Number.isFinite(target))return NaN;let n=target;for(let i=0;i<3;i++){const shown=Date.parse(localInput(n)+'Z');n+=target-shown;}return localInput(n)===s?n:NaN;}
const memberName=(s:State,id:string)=>s.members.find(m=>m.id===id)?.name??'Familiar';
const actionName=(a:string)=>a==='created'?'creó':a==='modified'?'modificó':'canceló';
async function api(path:string,method='GET',body?:unknown){const r=await authenticatedFetch('/api/'+path,{method,headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined,cache:'no-store'});const data:any=await r.json();if(!r.ok)throw new Error(data.error||'No se ha podido completar la operación.');return data;}
function Modal({title,children,onClose}:{title:string;children:React.ReactNode;onClose:()=>void}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();const before=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=before;};},[]);return <dialog ref={ref} aria-label={title} onCancel={onClose} onClick={e=>{if(e.target===ref.current)onClose();}} className="modal"><div className="modal-head"><h2>{title}</h2><button className="icon-btn" onClick={onClose} aria-label="Cerrar"><X size={22}/></button></div>{children}</dialog>;}
export default function Garage(){
 const [data,setData]=useState<State|null>(null),[error,setError]=useState(''),[tab,setTab]=useState('availability'),[day,setDay]=useState(dayKey(Date.now())),[editing,setEditing]=useState<Reservation|null|undefined>(undefined),[car,setCar]=useState('Passat'),[toast,setToast]=useState(''),[refreshing,setRefreshing]=useState(false),[noticeOpen,setNoticeOpen]=useState(false),[permission,setPermission]=useState('default'),[family,setFamily]=useState<any[]>([]),[savingFamily,setSavingFamily]=useState(false),[lastSeen,setLastSeen]=useState(0),[cancelTarget,setCancelTarget]=useState<Reservation|null>(null);
 const seenEvents=useRef<Set<string>|null>(null),reminded=useRef(new Set<string>()),offset=useRef(0);
 const showToast=useCallback((msg:string)=>{setToast(msg);},[]);
 const load=useCallback(async()=>{try{const s:State=await api('state');offset.current=s.serverTime-Date.now();setData(s);setError('');if(seenEvents.current){for(const e of s.events){if(!seenEvents.current.has(e.id)&&e.actor!==s.me.id&&(e.payload.participants.includes(s.me.id)||e.payload.previousParticipants?.includes(s.me.id))){const message=`${memberName(s,e.actor)} ${actionName(e.action)} una reserva del ${e.payload.car}.`;showToast(message);if(typeof Notification!=='undefined'&&Notification.permission==='granted')navigator.serviceWorker?.ready.then(sw=>sw.showNotification('Hinata Garaje',{body:message,tag:e.id,icon:'/hinata-driver-bn.png'}));}}}seenEvents.current=new Set(s.events.map(e=>e.id));}catch(e){setError((e as Error).message);}},[showToast]);
 useEffect(()=>{load();const poll=setInterval(load,10000);const focus=()=>load();window.addEventListener('focus',focus);navigator.serviceWorker?.register('/sw.js').catch(()=>{});if(typeof Notification!=='undefined')setPermission(Notification.permission);setLastSeen(Number(localStorage.getItem('garaje-last-seen')||0));return()=>{clearInterval(poll);window.removeEventListener('focus',focus);};},[load]);
 useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),6500);return()=>clearTimeout(timer);},[toast]);
 useEffect(()=>{if(!data)return;const tick=()=>{const now=Date.now()+offset.current;for(const r of data.reservations){const key=r.id+'-'+r.version;if(r.participants.includes(data.me.id)&&r.start>now&&r.start-now<=1800000&&!reminded.current.has(key)){reminded.current.add(key);const message=`Tu reserva del ${r.car} empieza a las ${time(r.start)}.`;showToast(message);if(typeof Notification!=='undefined'&&Notification.permission==='granted')navigator.serviceWorker?.ready.then(sw=>sw.showNotification('Hinata · Tu coche, en 30 minutos',{body:message,tag:key,icon:'/hinata-driver-bn.png'}));}}};tick();const timer=setInterval(tick,15000);return()=>clearInterval(timer);},[data,showToast]);
 async function refresh(){setRefreshing(true);await load();setRefreshing(false);}
 async function enableNotices(){if(typeof Notification==='undefined'){showToast('Este navegador no admite estos avisos. Usa el recordatorio del calendario.');return;}const p=await Notification.requestPermission();setPermission(p);showToast(p==='granted'?'Avisos activados mientras la app está abierta.':'Puedes usar los recordatorios del calendario.');}
 const now=Date.now()+offset.current;
 const dates=Array.from({length:8},(_,i)=>{const n=fromInput(dayKey(now)+'T12:00')+i*86400000;return{key:dayKey(n),n};});
 const dayStart=fromInput(day+'T00:00'),dayEnd=fromInput(dayKey(dayStart+36*3600000)+'T00:00');
 const daily=data?.reservations.filter(r=>overlaps(r,{start:dayStart,end:dayEnd}))??[];
 const notices=data?.events.filter(e=>e.payload.participants.includes(data.me.id)||e.payload.previousParticipants?.includes(data.me.id))??[];
 const unread=notices.filter(e=>e.at>lastSeen&&e.actor!==data?.me.id).length;
 function openNotices(){setNoticeOpen(true);setLastSeen(now);localStorage.setItem('garaje-last-seen',String(now));}
 function newBooking(c='Passat'){setCar(c);setEditing(null);}
 async function calendar(r:Reservation){try{await download('/api/calendar?id='+encodeURIComponent(r.id),'reserva.ics');}catch(e){showToast((e as Error).message);}}
 async function cancel(){if(!cancelTarget)return;try{await api('reservations','DELETE',{id:cancelTarget.id,version:cancelTarget.version});setCancelTarget(null);await load();showToast('Reserva cancelada. El horario vuelve a estar disponible.');}catch(e){showToast((e as Error).message);}}
 useEffect(()=>{if(data)setFamily(data.members.map(m=>({...m,email:m.email||''})));},[data?.members.map(m=>m.name+m.email).join('|')]);
 async function saveFamily(e:React.FormEvent){e.preventDefault();setSavingFamily(true);try{await api('members','PUT',{members:family});await load();showToast('Familia actualizada.');}catch(e){showToast((e as Error).message);}finally{setSavingFamily(false);}}
 function row(r:Reservation){return <article className="reservation" key={r.id}><span className={'car-stripe '+r.car.toLowerCase()}/><div className="reservation-time"><strong>{time(r.start)}</strong><span>{time(r.end)}</span></div><div className="reservation-body"><div className="row-heading"><strong>{r.car}</strong>{r.override===1&&<span className="exception"><ShieldCheck size={13}/> Excepción</span>}</div><p>{r.participants.map(id=>memberName(data!,id)).join(', ')}</p>{r.note&&<p className="note">{r.note}</p>}<small>{date(r.start,{day:'numeric',month:'short'})}{dayKey(r.start)!==dayKey(r.end)?' – '+date(r.end,{day:'numeric',month:'short'}):''} · Creada por {memberName(data!,r.creator)}</small></div><div className="row-actions"><button className="icon-btn" onClick={()=>calendar(r)} aria-label="Añadir recordatorio al calendario" title="Recordatorio del calendario"><CalendarPlus size={19}/></button>{(data!.me.admin||r.creator===data!.me.id)&&<><button className="icon-btn" onClick={()=>setEditing(r)} aria-label="Editar reserva"><Pencil size={18}/></button><button className="icon-btn danger" onClick={()=>setCancelTarget(r)} aria-label="Cancelar reserva"><Trash2 size={18}/></button></>}</div></article>;}
 return <div className="app"><header className="header"><a href="/" className="brand"><span className="brand-icon"><img src="/hinata-driver-bn.png" alt=""/></span><span>Hinata Garaje<span className="brand-sub">Passat y Mazda</span></span></a><div className="header-right"><button className="icon-btn notice-button" onClick={openNotices} aria-label={`Avisos${unread?' · '+unread+' sin leer':''}`}><Bell size={21}/>{unread>0&&<span className="notice-count">{unread}</span>}</button><span className="profile-avatar">{data?.me.name.slice(0,1).toUpperCase()||'…'}</span><span className="profile-name">{data?.me.name||'Tu familia'}<small>{data?.me.admin?'Administrador':'Familiar'}</small></span></div></header>
 <main className="main"><nav className="tabs" aria-label="Secciones"><button onClick={()=>setTab('availability')} className={tab==='availability'?'selected':''}><CalendarDays size={19}/>Calendario</button><button onClick={()=>setTab('mine')} className={tab==='mine'?'selected':''}><Car size={19}/>Reservas</button><button onClick={()=>setTab('family')} className={tab==='family'?'selected':''}><Users size={19}/>Familia</button>{data?.me.admin===1&&<button onClick={()=>setTab('history')} className={tab==='history'?'selected':''}><History size={19}/>Historial</button>}</nav>
 {error&&<div className="alert"><WifiOff size={20}/><span>{error} {data?'La disponibilidad puede estar desactualizada.':''}</span><button onClick={refresh}>Reintentar</button><button onClick={()=>signOut(auth())}>Cerrar sesión</button></div>}
 {!data&&!error&&<div className="loading"><RefreshCw className="spin"/> Consultando el garaje…</div>}
 {data&&<>
 {tab==='availability'&&<><section className="page-title"><div><h1>¿Qué coche necesitas?</h1><p>Dos coches. Un calendario para todos.</p></div><button className="primary" onClick={()=>newBooking()} disabled={!!error}><Plus size={20}/>Nueva reserva</button></section>
 <section className="cars" aria-label="Estado actual de los coches">{['Passat','Mazda'].map(c=>{const active=data.reservations.filter(r=>r.car===c&&r.start<=now&&r.end>now);const next=data.reservations.find(r=>r.car===c&&r.start>now);return <article key={c} className={'car-card '+c.toLowerCase()}><div className="car-card-top"><span className="car-name">{c}</span><span className={'status '+(active.length?'busy':'free')}>{active.length?'En uso':'Libre ahora'}</span></div><div className="car-card-main"><Car size={50} strokeWidth={1.3}/><div>{active.length?<><strong>Hasta las {time(Math.max(...active.map(r=>r.end)))}</strong><p>{[...new Set(active.flatMap(r=>r.participants))].map(id=>memberName(data,id)).join(', ')}</p></>:<><strong>Listo para salir</strong><p>{next?'Próxima reserva: '+date(next.start,{weekday:'short',day:'numeric',month:'short'})+' a las '+time(next.start):'Sin próximas reservas'}</p></>}</div></div><button className="car-book" onClick={()=>newBooking(c)} disabled={!!error}><Plus size={17}/>Reservar {c}</button></article>;})}</section>
 <section className="calendar-section"><div className="section-heading"><div><h2>El calendario familiar</h2><p>{date(dayStart,{month:'long',year:'numeric'})}</p></div><button className="text-button" onClick={refresh} disabled={refreshing}><RefreshCw size={16} className={refreshing?'spin':''}/>Actualizar</button></div><div className="day-strip">{dates.map(d=><button key={d.key} onClick={()=>setDay(d.key)} aria-pressed={day===d.key} className={day===d.key?'chosen':''}><span>{d.key===dayKey(now)?'Hoy':date(d.n,{weekday:'short'}).replace('.','')}</span><strong>{date(d.n,{day:'numeric'})}</strong><span className="day-reservations">{data.reservations.filter(r=>overlaps(r,{start:fromInput(d.key+'T00:00'),end:fromInput(dayKey(d.n+86400000)+'T00:00')})).length||'—'}</span></button>)}</div>
 <div className="timeline"><div className="timeline-label"/><div className="timeline-ticks">{['00:00','06:00','12:00','18:00','24:00'].map(t=><span key={t}>{t}</span>)}</div>{['Passat','Mazda'].map(c=><div className="lane" key={c}><strong>{c}</strong><div className="lane-track">{daily.filter(r=>r.car===c).map((r,i)=>{const left=Math.max(0,(r.start-dayStart)/(dayEnd-dayStart)*100),width=Math.min(100,(r.end-dayStart)/(dayEnd-dayStart)*100)-left;return <button key={r.id} title={`${c}: ${time(r.start)}–${time(r.end)}, ${r.participants.map(id=>memberName(data,id)).join(', ')}`} onClick={()=>{if(data.me.admin||r.creator===data.me.id)setEditing(r);else showToast(`${c}: ${time(r.start)}–${time(r.end)} · ${r.participants.map(id=>memberName(data,id)).join(', ')}`);}} className={'time-block '+c.toLowerCase()} style={{left:left+'%',width:Math.max(width,1)+'%',top:r.override?`${4+(i%2)*8}px`:undefined}}><span>{time(r.start)}</span></button>;})}</div></div>)}</div>
 <div className="agenda-heading"><h3>{day===dayKey(now)?'Reservas de hoy':date(dayStart,{weekday:'long',day:'numeric',month:'long'})}</h3><span>{daily.length} {daily.length===1?'reserva':'reservas'}</span></div>{daily.length?daily.map(row):<div className="empty"><CalendarDays size={30}/><div><strong>El día está libre</strong><p>Reserva el coche y añade a quienes vayan contigo.</p></div><button className="secondary" onClick={()=>newBooking()} disabled={!!error}>Reservar</button></div>}
 </section><div className="rules-bar"><span><Clock size={16}/>Hasta 10 horas</span><span><CalendarDays size={16}/>168 h de antelación</span><span><Users size={16}/>Sin solapamientos</span></div></>}
 {tab==='mine'&&<><section className="page-title"><div><h1>Mis reservas</h1><p>Las que organizas y aquellas en las que participas.</p></div><button className="primary" onClick={()=>newBooking()} disabled={!!error}><Plus size={20}/>Nueva reserva</button></section>{['upcoming','past'].map(kind=>{const rs=data.reservations.filter(r=>(r.creator===data.me.id||r.participants.includes(data.me.id))&&(kind==='upcoming'?r.end>now:r.end<=now));return <section className="list-section" key={kind}><h2>{kind==='upcoming'?'Próximas':'Terminadas'}</h2>{rs.length?rs.map(row):<div className="empty"><CalendarDays size={28}/><p>{kind==='upcoming'?'No tienes próximas reservas.':'Todavía no hay reservas terminadas.'}</p></div>}</section>;})}<section className="reminder-panel"><Bell size={25}/><div><h3>Un aviso antes de salir</h3><p>Añade cada reserva al calendario del móvil para recibir el recordatorio 30 minutos antes, incluso con esta app cerrada. Si editas la reserva, actualiza también el evento del calendario.</p><button className="secondary" onClick={enableNotices}>{permission==='granted'?'Avisos de la app activados':'Activar avisos de la app'}</button><small>Los avisos de cambios y los recordatorios de la app requieren que permanezca abierta.</small></div></section></>}
 {tab==='family'&&<><section className="page-title"><div><h1>La familia</h1><p>Cuatro personas, un garaje compartido.</p></div><span className="family-badge"><Users size={18}/>4 miembros</span></section>{data.me.admin?<form className="family-form" onSubmit={saveFamily}><p className="setting-info">Configura el nombre y el correo con el que cada familiar iniciará sesión. Solo estos correos podrán acceder a las reservas.</p>{family.map((m,i)=><div className="member-edit" key={m.id}><span className={'avatar member-'+i}>{m.name.slice(0,1).toUpperCase()}</span><label>Nombre<input required maxLength={50} value={m.name} onChange={e=>setFamily(family.map(x=>x.id===m.id?{...x,name:e.target.value}:x))}/></label><label>Correo de acceso<input type="email" value={m.email} disabled={m.id===data.me.id} placeholder="correo@ejemplo.com" onChange={e=>setFamily(family.map(x=>x.id===m.id?{...x,email:e.target.value}:x))}/></label><span className="role">{m.admin?'Administrador':'Familiar'}</span></div>)}<div className="form-footer"><button className="primary" disabled={savingFamily||!!error}>{savingFamily?'Guardando…':'Guardar familia'}</button></div></form>:<div className="family-list">{data.members.map((m,i)=><div className="member-edit" key={m.id}><span className={'avatar member-'+i}>{m.name.slice(0,1).toUpperCase()}</span><strong>{m.name}</strong><span className="role">{m.admin?'Administrador':'Familiar'}</span></div>)}</div>}<section className="settings-bottom"><div><h3><Bell size={19}/>Avisos en este dispositivo</h3><p>Permite los avisos para ver cambios mientras la app está abierta.</p><button className="secondary" onClick={enableNotices}>{permission==='granted'?'Avisos activados':'Permitir avisos'}</button></div><div><h3><Download size={19}/>Añadir al móvil</h3><p>En iPhone: Safari → Compartir → Añadir a pantalla de inicio. En Android: menú del navegador → Instalar app o Añadir a pantalla de inicio.</p></div></section>{data.me.admin===1&&<section className="backup"><div><h3>Copia de tus datos</h3><p>Descarga reservas, familia e historial en un archivo.</p></div><button className="secondary" onClick={async()=>{try{await download("/api/backup","garaje-copia.json");}catch(e){showToast((e as Error).message);}}}><Download size={17}/>Descargar copia</button></section>}<button className="signout" onClick={()=>signOut(auth())}><LogOut size={17}/>Cerrar sesión</button></>}
 {tab==='history'&&data.me.admin===1&&<><section className="page-title"><div><h1>Historial de cambios</h1><p>Quién reservó, modificó o canceló cada coche.</p></div><ShieldCheck size={30}/></section><section className="history-list">{data.events.length?data.events.map(e=><article key={e.id} className="event"><span className="event-icon">{e.action==='cancelled'?<Trash2 size={18}/>:e.action==='modified'?<Pencil size={18}/>:<Plus size={18}/>}</span><div><p><strong>{memberName(data,e.actor)}</strong> {actionName(e.action)} una reserva del <strong>{e.payload.car}</strong></p><span>{date(e.payload.start,{day:'numeric',month:'short'})}, {time(e.payload.start)}–{time(e.payload.end)} · {e.payload.participants.map((id:string)=>memberName(data,id)).join(', ')}</span>{!!e.payload.override&&<p className="event-exception">Excepción de administrador{e.payload.violations?.length?': '+e.payload.violations.join(' '):''}</p>}</div><time>{date(e.at,{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})}</time></article>):<div className="empty"><History size={30}/><p>Aquí aparecerán los cambios de las reservas.</p></div>}</section></>}
 </>}
 <footer className="footer"><span>Hinata Garaje</span><span>{error?'Sin sincronizar':data?'Actualización cada 10 segundos':'Conectando…'} · Hora de Madrid</span></footer></main>
 {data&&editing!==undefined&&<Booking data={data} existing={editing} initialCar={car} initialDay={day} now={now} onClose={()=>setEditing(undefined)} onSaved={async()=>{setEditing(undefined);await load();showToast('Reserva guardada y compartida con la familia.');}}/>}
 {noticeOpen&&<Modal title="Avisos" onClose={()=>setNoticeOpen(false)}><div className="modal-body">{notices.length?notices.slice(0,30).map(e=><div className="notice" key={e.id}><Bell size={18}/><div><p>{data&&memberName(data,e.actor)} {actionName(e.action)} una reserva del {e.payload.car}.</p><small>{date(e.at,{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})}</small></div></div>):<div className="empty"><Bell size={28}/><p>No tienes avisos todavía.</p></div>}<div className="info-box">Los avisos se actualizan mientras la app está abierta. Para recibir un recordatorio con la app cerrada, añade la reserva al calendario del móvil.</div></div></Modal>}
 {cancelTarget&&<Modal title="Cancelar reserva" onClose={()=>setCancelTarget(null)}><div className="modal-body"><p>Se liberará el {cancelTarget.car} el {date(cancelTarget.start,{day:'numeric',month:'long'})}, de {time(cancelTarget.start)} a {time(cancelTarget.end)}.</p><div className="modal-actions"><button className="secondary" onClick={()=>setCancelTarget(null)}>Conservar reserva</button><button className="danger-btn" onClick={cancel}>Cancelar reserva</button></div></div></Modal>}
 {toast&&<div className="toast" role="status"><Check size={20}/><span>{toast}</span><button aria-label="Cerrar aviso" onClick={()=>setToast('')}><X size={17}/></button></div>}
 </div>;
}
function Booking({data,existing,initialCar,initialDay,now,onClose,onSaved}:{data:State;existing:Reservation|null;initialCar:string;initialDay:string;now:number;onClose:()=>void;onSaved:()=>Promise<void>}){
 const initial=existing?.start??Math.max(fromInput(initialDay+'T09:00'),Math.ceil((now+300000)/900000)*900000);
 const [car,setCar]=useState(existing?.car??initialCar),[start,setStart]=useState(localInput(initial)),[end,setEnd]=useState(localInput(existing?.end??initial+3600000)),[participants,setParticipants]=useState<string[]>(existing?.participants??[data.me.id]),[note,setNote]=useState(existing?.note??''),[override,setOverride]=useState(false),[confirmed,setConfirmed]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const s=fromInput(start),e=fromInput(end);const shape={car,start:s,end:e,participants};
 const valid=Number.isFinite(s)&&Number.isFinite(e)&&e>s&&participants.length>0;
 const issues=valid?violations(shape,data.reservations.filter(r=>r.id!==existing?.id),data.members,now):[];
 function resetOverride(){setConfirmed(false);setError('');}
 async function submit(event:React.FormEvent){event.preventDefault();setError('');if(!valid){setError('Selecciona un horario válido y al menos una persona.');return;}if(issues.length&&!override){setError('Resuelve los conflictos antes de guardar.');return;}if(override&&!confirmed){setError('Confirma la excepción antes de guardar.');return;}setBusy(true);try{await api('reservations',existing?'PUT':'POST',{...shape,note,override,id:existing?.id,version:existing?.version});await onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <Modal title={existing?'Editar reserva':'Nueva reserva'} onClose={onClose}><form onSubmit={submit} className="booking-form"><fieldset><legend>Elige coche</legend><div className="car-choice">{['Passat','Mazda'].map(c=><button type="button" key={c} onClick={()=>{setCar(c);resetOverride();}} className={car===c?'active '+c.toLowerCase():''} aria-pressed={car===c}><Car size={24}/><strong>{c}</strong>{car===c&&<Check size={19}/>}</button>)}</div></fieldset><div className="date-inputs"><label>Inicio<input type="datetime-local" required value={start} onChange={ev=>{setStart(ev.target.value);resetOverride();}}/></label><label>Fin<input type="datetime-local" required value={end} onChange={ev=>{setEnd(ev.target.value);resetOverride();}}/></label></div><p className="input-hint">Hora de Madrid{valid?' · '+((e-s)/3600000).toLocaleString('es-ES',{maximumFractionDigits:2})+' h':''} · Máximo 10 h</p><fieldset><legend>¿Quién va?</legend><p className="input-hint">Todas las personas seleccionadas quedan ocupadas.</p><div className="people-choice">{data.members.map((m,i)=><label key={m.id} className={participants.includes(m.id)?'picked':''}><input type="checkbox" checked={participants.includes(m.id)} onChange={()=>{setParticipants(ps=>ps.includes(m.id)?ps.filter(id=>id!==m.id):[...ps,m.id]);resetOverride();}}/><span className={'avatar member-'+i}>{m.name.slice(0,1).toUpperCase()}</span><span>{m.name}</span></label>)}</div></fieldset><label>Nota <span className="optional">Opcional</span><textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={500} rows={2} placeholder="Por ejemplo, recogida en la estación"/></label>
 {issues.length>0&&<div className="conflicts" role="status"><strong><TriangleAlert size={18}/>Revisa la reserva</strong><ul>{issues.map(i=><li key={i}>{i}</li>)}</ul></div>}
 {data.me.admin===1&&<div className="override"><label className="checkbox-line"><input type="checkbox" checked={override} onChange={e=>{setOverride(e.target.checked);setConfirmed(false);}}/><ShieldCheck size={18}/><span>Aplicar excepción de administrador</span></label>{override&&<div className="override-confirm"><p>Esta reserva podrá superar los límites y solaparse con otras. La excepción quedará registrada.</p><label className="checkbox-line"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><span>Confirmo que quiero guardar esta excepción.</span></label></div>}</div>}
 {error&&<div className="alert" role="alert">{error}</div>}<div className="modal-actions"><button type="button" className="secondary" onClick={onClose} disabled={busy}>Volver</button><button className="primary" disabled={busy||!valid||(issues.length>0&&!override)||(override&&!confirmed)}>{busy?'Guardando…':existing?'Guardar cambios':'Confirmar reserva'}</button></div></form></Modal>;
}
