'use client';
import {authenticatedFetch,download,auth} from '../lib/firebase-client';
import CarThumbnail from './car-thumbnail';
import {signOut} from 'firebase/auth';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Car,CalendarDays,Plus,Users,Clock,ShieldCheck,Bell,X,Check,Download,RefreshCw,LogOut,TriangleAlert,History,CalendarPlus,Pencil,Trash2,WifiOff} from 'lucide-react';
import {Member,Reservation,violations,overlaps} from '../lib/rules';
type Event={id:string;reservation:string;actor:string;action:string;at:number;payload:any};
type State={me:Member;members:Member[];reservations:Reservation[];events:Event[];serverTime:number};
const ZONE='Europe/Madrid';
const date=(n:number,opts:Intl.DateTimeFormatOptions={})=>new Intl.DateTimeFormat('ca-ES',{timeZone:ZONE,...opts}).format(n);
const time=(n:number)=>date(n,{hour:'2-digit',minute:'2-digit'});
const dayKey=(n:number)=>new Intl.DateTimeFormat('sv-SE',{timeZone:ZONE,year:'numeric',month:'2-digit',day:'2-digit'}).format(n);
function localInput(n:number){const parts=new Intl.DateTimeFormat('sv-SE',{timeZone:ZONE,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(n);return parts.replace(' ','T');}
function fromInput(s:string){const target=Date.parse(s+'Z');if(!Number.isFinite(target))return NaN;let n=target;for(let i=0;i<3;i++){const shown=Date.parse(localInput(n)+'Z');n+=target-shown;}return localInput(n)===s?n:NaN;}
const memberName=(s:State,id:string)=>s.members.find(m=>m.id===id)?.name??'Familiar';
const actionName=(a:string)=>a==='created'?'ha creat':a==='modified'?'ha modificat':'ha cancel·lat';
async function api(path:string,method='GET',body?:unknown){const r=await authenticatedFetch('/api/'+path,{method,headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined,cache:'no-store'});const data:any=await r.json();if(!r.ok)throw new Error(data.error||'No s’ha pogut completar l’operació.');return data;}
function Modal({title,children,onClose}:{title:string;children:React.ReactNode;onClose:()=>void}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();const before=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=before;};},[]);return <dialog ref={ref} aria-label={title} onCancel={onClose} onClick={e=>{if(e.target===ref.current)onClose();}} className="modal"><div className="modal-head"><h2>{title}</h2><button className="icon-btn" onClick={onClose} aria-label="Tancar"><X size={22}/></button></div>{children}</dialog>;}
export default function Garage(){
 const [data,setData]=useState<State|null>(null),[error,setError]=useState(''),[tab,setTab]=useState('availability'),[day,setDay]=useState(dayKey(Date.now())),[editing,setEditing]=useState<Reservation|null|undefined>(undefined),[car,setCar]=useState('Passat'),[toast,setToast]=useState(''),[refreshing,setRefreshing]=useState(false),[noticeOpen,setNoticeOpen]=useState(false),[permission,setPermission]=useState('default'),[family,setFamily]=useState<any[]>([]),[savingFamily,setSavingFamily]=useState(false),[lastSeen,setLastSeen]=useState(0),[cancelTarget,setCancelTarget]=useState<Reservation|null>(null);
 const seenEvents=useRef<Set<string>|null>(null),reminded=useRef(new Set<string>()),offset=useRef(0);
 const showToast=useCallback((msg:string)=>{setToast(msg);},[]);
 const load=useCallback(async()=>{try{const s:State=await api('state');offset.current=s.serverTime-Date.now();setData(s);setError('');if(seenEvents.current){for(const e of s.events){if(!seenEvents.current.has(e.id)&&e.actor!==s.me.id&&(e.payload.participants.includes(s.me.id)||e.payload.previousParticipants?.includes(s.me.id))){const message=`${memberName(s,e.actor)} ${actionName(e.action)} una reserva del ${e.payload.car}.`;showToast(message);if(typeof Notification!=='undefined'&&Notification.permission==='granted')navigator.serviceWorker?.ready.then(sw=>sw.showNotification('Hinata Garatge',{body:message,tag:e.id,icon:'/hinata-driver-bn.png'}));}}}seenEvents.current=new Set(s.events.map(e=>e.id));}catch(e){setError((e as Error).message);}},[showToast]);
 useEffect(()=>{load();const poll=setInterval(load,10000);const focus=()=>load();window.addEventListener('focus',focus);navigator.serviceWorker?.register('/sw.js').catch(()=>{});if(typeof Notification!=='undefined')setPermission(Notification.permission);setLastSeen(Number(localStorage.getItem('garaje-last-seen')||0));return()=>{clearInterval(poll);window.removeEventListener('focus',focus);};},[load]);
 useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),6500);return()=>clearTimeout(timer);},[toast]);
 useEffect(()=>{if(!data)return;const tick=()=>{const now=Date.now()+offset.current;for(const r of data.reservations){const key=r.id+'-'+r.version;if(r.participants.includes(data.me.id)&&r.start>now&&r.start-now<=1800000&&!reminded.current.has(key)){reminded.current.add(key);const message=`La teva reserva del ${r.car} comença a les ${time(r.start)}.`;showToast(message);if(typeof Notification!=='undefined'&&Notification.permission==='granted')navigator.serviceWorker?.ready.then(sw=>sw.showNotification('Hinata · El teu cotxe, d’aquí a 30 minuts',{body:message,tag:key,icon:'/hinata-driver-bn.png'}));}}};tick();const timer=setInterval(tick,15000);return()=>clearInterval(timer);},[data,showToast]);
 async function refresh(){setRefreshing(true);await load();setRefreshing(false);}
 async function enableNotices(){if(typeof Notification==='undefined'){showToast('Aquest navegador no admet aquests avisos. Fes servir el recordatori del calendari.');return;}const p=await Notification.requestPermission();setPermission(p);showToast(p==='granted'?'Avisos activats mentre l’app està oberta.':'Pots fer servir els recordatoris del calendari.');}
 const now=Date.now()+offset.current;
 const dates=Array.from({length:8},(_,i)=>{const n=fromInput(dayKey(now)+'T12:00')+i*86400000;return{key:dayKey(n),n};});
 const dayStart=fromInput(day+'T00:00'),dayEnd=fromInput(dayKey(dayStart+36*3600000)+'T00:00');
 const daily=data?.reservations.filter(r=>overlaps(r,{start:dayStart,end:dayEnd}))??[];
 const notices=data?.events.filter(e=>e.payload.participants.includes(data.me.id)||e.payload.previousParticipants?.includes(data.me.id))??[];
 const unread=notices.filter(e=>e.at>lastSeen&&e.actor!==data?.me.id).length;
 function openNotices(){setNoticeOpen(true);setLastSeen(now);localStorage.setItem('garaje-last-seen',String(now));}
 function newBooking(c='Passat'){setCar(c);setEditing(null);}
 async function calendar(r:Reservation){try{await download('/api/calendar?id='+encodeURIComponent(r.id),'reserva.ics');}catch(e){showToast((e as Error).message);}}
 async function cancel(){if(!cancelTarget)return;try{await api('reservations','DELETE',{id:cancelTarget.id,version:cancelTarget.version});setCancelTarget(null);await load();showToast('Reserva cancel·lada. L’horari torna a estar disponible.');}catch(e){showToast((e as Error).message);}}
 useEffect(()=>{if(data)setFamily(data.members.map(m=>({...m,email:m.email||''})));},[data?.members.map(m=>m.name+m.email).join('|')]);
 async function saveFamily(e:React.FormEvent){e.preventDefault();setSavingFamily(true);try{await api('members','PUT',{members:family});await load();showToast('Família actualitzada.');}catch(e){showToast((e as Error).message);}finally{setSavingFamily(false);}}
 function row(r:Reservation){return <article className="reservation" key={r.id}><span className={'car-stripe '+r.car.toLowerCase()}/><div className="reservation-time"><strong>{time(r.start)}</strong><span>{time(r.end)}</span></div><div className="reservation-body"><div className="row-heading"><strong>{r.car}</strong>{r.override===1&&<span className="exception"><ShieldCheck size={13}/> Excepció</span>}</div><p>{r.participants.map(id=>memberName(data!,id)).join(', ')}</p>{r.note&&<p className="note">{r.note}</p>}<small>{date(r.start,{day:'numeric',month:'short'})}{dayKey(r.start)!==dayKey(r.end)?' – '+date(r.end,{day:'numeric',month:'short'}):''} · Creada per {memberName(data!,r.creator)}</small></div><div className="row-actions"><button className="icon-btn" onClick={()=>calendar(r)} aria-label="Afegir un recordatori al calendari" title="Recordatori del calendari"><CalendarPlus size={19}/></button>{(data!.me.admin||r.creator===data!.me.id)&&<><button className="icon-btn" onClick={()=>setEditing(r)} aria-label="Editar la reserva"><Pencil size={18}/></button><button className="icon-btn danger" onClick={()=>setCancelTarget(r)} aria-label="Cancel·lar la reserva"><Trash2 size={18}/></button></>}</div></article>;}
 return <div className="app"><header className="header"><a href="/" className="brand"><span className="brand-icon"><img src="/hinata-driver-bn.png" alt=""/></span><span>Hinata Garatge<span className="brand-sub">Passat i Mazda</span></span></a><div className="header-right"><button className="icon-btn notice-button" onClick={openNotices} aria-label={`Avisos${unread?' · '+unread+' sense llegir':''}`}><Bell size={21}/>{unread>0&&<span className="notice-count">{unread}</span>}</button><span className="profile-avatar">{data?.me.name.slice(0,1).toUpperCase()||'…'}</span><span className="profile-name">{data?.me.name||'La teva família'}<small>{data?.me.admin?'Administrador':'Familiar'}</small></span></div></header>
 <main className="main"><nav className="tabs" aria-label="Seccions"><button onClick={()=>setTab('availability')} className={tab==='availability'?'selected':''}><CalendarDays size={19}/>Calendari</button><button onClick={()=>setTab('mine')} className={tab==='mine'?'selected':''}><Car size={19}/>Reserves</button><button onClick={()=>setTab('family')} className={tab==='family'?'selected':''}><Users size={19}/>Família</button>{data?.me.admin===1&&<button onClick={()=>setTab('history')} className={tab==='history'?'selected':''}><History size={19}/>Historial</button>}</nav>
 {error&&<div className="alert"><WifiOff size={20}/><span>{error} {data?'La disponibilitat pot estar desactualitzada.':''}</span><button onClick={refresh}>Tornar a provar</button><button onClick={()=>signOut(auth())}>Tancar la sessió</button></div>}
 {!data&&!error&&<div className="loading"><RefreshCw className="spin"/> Consultant el garatge…</div>}
 {data&&<>
 {tab==='availability'&&<><section className="page-title"><div><h1>Quin cotxe necessites?</h1><p>Dos cotxes. Un calendari per a tothom.</p></div><button className="primary" onClick={()=>newBooking()} disabled={!!error}><Plus size={20}/>Nova reserva</button></section>
 <section className="cars" aria-label="Estat actual dels cotxes">{['Passat','Mazda'].map(c=>{const active=data.reservations.filter(r=>r.car===c&&r.start<=now&&r.end>now);const next=data.reservations.find(r=>r.car===c&&r.start>now);return <article key={c} className={'car-card '+c.toLowerCase()}><div className="car-card-top"><span className="car-name">{c}</span><span className={'status '+(active.length?'busy':'free')}>{active.length?'En ús':'Lliure ara'}</span></div><div className="car-card-main"><CarThumbnail car={c}/><div>{active.length?<><strong>Fins a les {time(Math.max(...active.map(r=>r.end)))}</strong><p>{[...new Set(active.flatMap(r=>r.participants))].map(id=>memberName(data,id)).join(', ')}</p></>:<><strong>A punt per sortir</strong><p>{next?'Pròxima reserva: '+date(next.start,{weekday:'short',day:'numeric',month:'short'})+' a les '+time(next.start):'Sense pròximes reserves'}</p></>}</div></div><button className="car-book" onClick={()=>newBooking(c)} disabled={!!error}><Plus size={17}/>Reservar {c}</button></article>;})}</section>
 <section className="calendar-section"><div className="section-heading"><div><h2>El calendari familiar</h2><p>{date(dayStart,{month:'long',year:'numeric'})}</p></div><button className="text-button" onClick={refresh} disabled={refreshing}><RefreshCw size={16} className={refreshing?'spin':''}/>Actualitzar</button></div><div className="day-strip">{dates.map(d=><button key={d.key} onClick={()=>setDay(d.key)} aria-pressed={day===d.key} className={day===d.key?'chosen':''}><span>{d.key===dayKey(now)?'Avui':date(d.n,{weekday:'short'}).replace('.','')}</span><strong>{date(d.n,{day:'numeric'})}</strong><span className="day-reservations">{data.reservations.filter(r=>overlaps(r,{start:fromInput(d.key+'T00:00'),end:fromInput(dayKey(d.n+86400000)+'T00:00')})).length||'—'}</span></button>)}</div>
 <div className="timeline"><div className="timeline-label"/><div className="timeline-ticks">{['00:00','06:00','12:00','18:00','24:00'].map(t=><span key={t}>{t}</span>)}</div>{['Passat','Mazda'].map(c=><div className="lane" key={c}><strong>{c}</strong><div className="lane-track">{daily.filter(r=>r.car===c).map((r,i)=>{const left=Math.max(0,(r.start-dayStart)/(dayEnd-dayStart)*100),width=Math.min(100,(r.end-dayStart)/(dayEnd-dayStart)*100)-left;return <button key={r.id} title={`${c}: ${time(r.start)}–${time(r.end)}, ${r.participants.map(id=>memberName(data,id)).join(', ')}`} onClick={()=>{if(data.me.admin||r.creator===data.me.id)setEditing(r);else showToast(`${c}: ${time(r.start)}–${time(r.end)} · ${r.participants.map(id=>memberName(data,id)).join(', ')}`);}} className={'time-block '+c.toLowerCase()} style={{left:left+'%',width:Math.max(width,1)+'%',top:r.override?`${4+(i%2)*8}px`:undefined}}><span>{time(r.start)}</span></button>;})}</div></div>)}</div>
 <div className="agenda-heading"><h3>{day===dayKey(now)?'Reserves d’avui':date(dayStart,{weekday:'long',day:'numeric',month:'long'})}</h3><span>{daily.length} {daily.length===1?'reserva':'reserves'}</span></div>{daily.length?daily.map(row):<div className="empty"><CalendarDays size={30}/><div><strong>El dia està lliure</strong><p>Reserva el cotxe i afegeix les persones que t’acompanyaran.</p></div><button className="secondary" onClick={()=>newBooking()} disabled={!!error}>Reservar</button></div>}
 </section><div className="rules-bar"><span><Clock size={16}/>Fins a 10 hores</span><span><CalendarDays size={16}/>168 h d’antelació</span><span><Users size={16}/>Sense solapaments</span></div></>}
 {tab==='mine'&&<><section className="page-title"><div><h1>Les meves reserves</h1><p>Les que organitzes i les que comparteixes.</p></div><button className="primary" onClick={()=>newBooking()} disabled={!!error}><Plus size={20}/>Nova reserva</button></section>{['upcoming','past'].map(kind=>{const rs=data.reservations.filter(r=>(r.creator===data.me.id||r.participants.includes(data.me.id))&&(kind==='upcoming'?r.end>now:r.end<=now));return <section className="list-section" key={kind}><h2>{kind==='upcoming'?'Pròximes':'Finalitzades'}</h2>{rs.length?rs.map(row):<div className="empty"><CalendarDays size={28}/><p>{kind==='upcoming'?'No tens pròximes reserves.':'Encara no hi ha reserves finalitzades.'}</p></div>}</section>;})}<section className="reminder-panel"><Bell size={25}/><div><h3>Un avís abans de sortir</h3><p>Afegeix cada reserva al calendari del mòbil per rebre el recordatori 30 minuts abans, també amb l’app tancada. Si edites la reserva, actualitza també l’esdeveniment del calendari.</p><button className="secondary" onClick={enableNotices}>{permission==='granted'?'Avisos de l’app activats':'Activar els avisos de l’app'}</button><small>Els avisos de canvis i els recordatoris de l’app requereixen que estigui oberta.</small></div></section></>}
 {tab==='family'&&<><section className="page-title"><div><h1>La família</h1><p>Quatre persones, un garatge compartit.</p></div><span className="family-badge"><Users size={18}/>4 membres</span></section>{data.me.admin?<form className="family-form" onSubmit={saveFamily}><p className="setting-info">Configura el nom i el correu amb què cada familiar iniciarà sessió. Només aquests correus podran accedir a les reserves.</p>{family.map((m,i)=><div className="member-edit" key={m.id}><span className={'avatar member-'+i}>{m.name.slice(0,1).toUpperCase()}</span><label>Nom<input required maxLength={50} value={m.name} onChange={e=>setFamily(family.map(x=>x.id===m.id?{...x,name:e.target.value}:x))}/></label><label>Correu d’accés<input type="email" value={m.email} disabled={m.id===data.me.id} placeholder="correu@exemple.cat" onChange={e=>setFamily(family.map(x=>x.id===m.id?{...x,email:e.target.value}:x))}/></label><span className="role">{m.admin?'Administrador':'Familiar'}</span></div>)}<div className="form-footer"><button className="primary" disabled={savingFamily||!!error}>{savingFamily?'Desant…':'Desar la família'}</button></div></form>:<div className="family-list">{data.members.map((m,i)=><div className="member-edit" key={m.id}><span className={'avatar member-'+i}>{m.name.slice(0,1).toUpperCase()}</span><strong>{m.name}</strong><span className="role">{m.admin?'Administrador':'Familiar'}</span></div>)}</div>}<section className="settings-bottom"><div><h3><Bell size={19}/>Avisos en aquest dispositiu</h3><p>Activa els avisos per veure els canvis mentre l’app està oberta.</p><button className="secondary" onClick={enableNotices}>{permission==='granted'?'Avisos activats':'Activar els avisos'}</button></div><div><h3><Download size={19}/>Afegir al mòbil</h3><p>A l’iPhone: Safari → Compartir → Afegir a la pantalla d’inici. A Android: menú del navegador → Instal·lar l’app o Afegir a la pantalla d’inici.</p></div></section>{data.me.admin===1&&<section className="backup"><div><h3>Còpia de les teves dades</h3><p>Descarrega les reserves, la família i l’historial en un fitxer.</p></div><button className="secondary" onClick={async()=>{try{await download("/api/backup","garaje-copia.json");}catch(e){showToast((e as Error).message);}}}><Download size={17}/>Descarregar una còpia</button></section>}<button className="signout" onClick={()=>signOut(auth())}><LogOut size={17}/>Tancar la sessió</button></>}
 {tab==='history'&&data.me.admin===1&&<><section className="page-title"><div><h1>Historial de canvis</h1><p>Qui ha reservat, modificat o cancel·lat cada cotxe.</p></div><ShieldCheck size={30}/></section><section className="history-list">{data.events.length?data.events.map(e=><article key={e.id} className="event"><span className="event-icon">{e.action==='cancelled'?<Trash2 size={18}/>:e.action==='modified'?<Pencil size={18}/>:<Plus size={18}/>}</span><div><p><strong>{memberName(data,e.actor)}</strong> {actionName(e.action)} una reserva del <strong>{e.payload.car}</strong></p><span>{date(e.payload.start,{day:'numeric',month:'short'})}, {time(e.payload.start)}–{time(e.payload.end)} · {e.payload.participants.map((id:string)=>memberName(data,id)).join(', ')}</span>{!!e.payload.override&&<p className="event-exception">Excepció d’administrador{e.payload.violations?.length?': '+e.payload.violations.join(' '):''}</p>}</div><time>{date(e.at,{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})}</time></article>):<div className="empty"><History size={30}/><p>Aquí apareixeran els canvis de les reserves.</p></div>}</section></>}
 </>}
 <footer className="footer"><span>Hinata Garatge</span><span>{error?'Sense sincronitzar':data?'Actualització cada 10 segons':'Connectant…'} · Hora de Madrid</span></footer></main>
 {data&&editing!==undefined&&<Booking data={data} existing={editing} initialCar={car} initialDay={day} now={now} onClose={()=>setEditing(undefined)} onSaved={async()=>{setEditing(undefined);await load();showToast('Reserva desada i compartida amb la família.');}}/>}
 {noticeOpen&&<Modal title="Avisos" onClose={()=>setNoticeOpen(false)}><div className="modal-body">{notices.length?notices.slice(0,30).map(e=><div className="notice" key={e.id}><Bell size={18}/><div><p>{data&&memberName(data,e.actor)} {actionName(e.action)} una reserva del {e.payload.car}.</p><small>{date(e.at,{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})}</small></div></div>):<div className="empty"><Bell size={28}/><p>Encara no tens avisos.</p></div>}<div className="info-box">Els avisos s’actualitzen mentre l’app està oberta. Per rebre un recordatori amb l’app tancada, afegeix la reserva al calendari del mòbil.</div></div></Modal>}
 {cancelTarget&&<Modal title="Cancel·lar la reserva" onClose={()=>setCancelTarget(null)}><div className="modal-body"><p>Quedarà lliure el {cancelTarget.car} el {date(cancelTarget.start,{day:'numeric',month:'long'})}, de {time(cancelTarget.start)} a {time(cancelTarget.end)}.</p><div className="modal-actions"><button className="secondary" onClick={()=>setCancelTarget(null)}>Conservar la reserva</button><button className="danger-btn" onClick={cancel}>Cancel·lar la reserva</button></div></div></Modal>}
 {toast&&<div className="toast" role="status"><Check size={20}/><span>{toast}</span><button aria-label="Tancar l’avís" onClick={()=>setToast('')}><X size={17}/></button></div>}
 </div>;
}
function Booking({data,existing,initialCar,initialDay,now,onClose,onSaved}:{data:State;existing:Reservation|null;initialCar:string;initialDay:string;now:number;onClose:()=>void;onSaved:()=>Promise<void>}){
 const initial=existing?.start??Math.max(fromInput(initialDay+'T09:00'),Math.ceil((now+300000)/900000)*900000);
 const [car,setCar]=useState(existing?.car??initialCar),[start,setStart]=useState(localInput(initial)),[end,setEnd]=useState(localInput(existing?.end??initial+3600000)),[participants,setParticipants]=useState<string[]>(existing?.participants??[data.me.id]),[note,setNote]=useState(existing?.note??''),[override,setOverride]=useState(false),[confirmed,setConfirmed]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const s=fromInput(start),e=fromInput(end);const shape={car,start:s,end:e,participants};
 const valid=Number.isFinite(s)&&Number.isFinite(e)&&e>s&&participants.length>0;
 const issues=valid?violations(shape,data.reservations.filter(r=>r.id!==existing?.id),data.members,now):[];
 function resetOverride(){setConfirmed(false);setError('');}
 async function submit(event:React.FormEvent){event.preventDefault();setError('');if(!valid){setError('Selecciona un horari vàlid i almenys una persona.');return;}if(issues.length&&!override){setError('Resol els conflictes abans de desar.');return;}if(override&&!confirmed){setError('Confirma l’excepció abans de desar.');return;}setBusy(true);try{await api('reservations',existing?'PUT':'POST',{...shape,note,override,id:existing?.id,version:existing?.version});await onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <Modal title={existing?'Editar la reserva':'Nova reserva'} onClose={onClose}><form onSubmit={submit} className="booking-form"><fieldset><legend>Tria el cotxe</legend><div className="car-choice">{['Passat','Mazda'].map(c=><button type="button" key={c} onClick={()=>{setCar(c);resetOverride();}} className={car===c?'active '+c.toLowerCase():''} aria-pressed={car===c}><CarThumbnail car={c}/><strong>{c}</strong>{car===c&&<Check size={19}/>}</button>)}</div></fieldset><div className="date-inputs"><label>Inici<input type="datetime-local" required value={start} onChange={ev=>{setStart(ev.target.value);resetOverride();}}/></label><label>Final<input type="datetime-local" required value={end} onChange={ev=>{setEnd(ev.target.value);resetOverride();}}/></label></div><p className="input-hint">Hora de Madrid{valid?' · '+((e-s)/3600000).toLocaleString('ca-ES',{maximumFractionDigits:2})+' h':''} · Màxim 10 h</p><fieldset><legend>Qui hi va?</legend><p className="input-hint">Totes les persones seleccionades queden ocupades.</p><div className="people-choice">{data.members.map((m,i)=><label key={m.id} className={participants.includes(m.id)?'picked':''}><input type="checkbox" checked={participants.includes(m.id)} onChange={()=>{setParticipants(ps=>ps.includes(m.id)?ps.filter(id=>id!==m.id):[...ps,m.id]);resetOverride();}}/><span className={'avatar member-'+i}>{m.name.slice(0,1).toUpperCase()}</span><span>{m.name}</span></label>)}</div></fieldset><label>Nota <span className="optional">Opcional</span><textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={500} rows={2} placeholder="Per exemple, recollida a l’estació"/></label>
 {issues.length>0&&<div className="conflicts" role="status"><strong><TriangleAlert size={18}/>Revisa la reserva</strong><ul>{issues.map(i=><li key={i}>{i}</li>)}</ul></div>}
 {data.me.admin===1&&<div className="override"><label className="checkbox-line"><input type="checkbox" checked={override} onChange={e=>{setOverride(e.target.checked);setConfirmed(false);}}/><ShieldCheck size={18}/><span>Aplicar una excepció d’administrador</span></label>{override&&<div className="override-confirm"><p>Aquesta reserva podrà superar els límits i coincidir amb altres reserves. L’excepció quedarà registrada.</p><label className="checkbox-line"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><span>Confirmo que vull desar aquesta excepció.</span></label></div>}</div>}
 {error&&<div className="alert" role="alert">{error}</div>}<div className="modal-actions"><button type="button" className="secondary" onClick={onClose} disabled={busy}>Tornar</button><button className="primary" disabled={busy||!valid||(issues.length>0&&!override)||(override&&!confirmed)}>{busy?'Desant…':existing?'Desar els canvis':'Confirmar la reserva'}</button></div></form></Modal>;
}
