import {cert,getApps,initializeApp} from 'firebase-admin/app';
import {getAuth} from 'firebase-admin/auth';
import {getFirestore,Transaction} from 'firebase-admin/firestore';
import {Member,Reservation,validShape,violations} from './rules';
export class AppError extends Error{constructor(public status:number,message:string){super(message);}}
function services(){const projectId=process.env.FIREBASE_PROJECT_ID,clientEmail=process.env.FIREBASE_CLIENT_EMAIL,privateKey=process.env.FIREBASE_PRIVATE_KEY;if(!projectId||!clientEmail||!privateKey||!process.env.FAMILY_ADMIN_EMAIL)throw new AppError(503,'Falta configurar Firebase en el servidor.');const app=getApps()[0]??initializeApp({credential:cert({projectId,clientEmail,privateKey:privateKey.replace(/\\n/g,'\n')})});return {db:getFirestore(app),auth:getAuth(app)};}
async function email(req:Request){const token=req.headers.get('authorization')?.match(/^Bearer (.+)$/)?.[1];if(!token)throw new AppError(401,'Inicia sesión para continuar.');try{const u=await services().auth.verifyIdToken(token,true);if(!u.email||!u.email_verified)throw new AppError(403,'Verifica tu correo.');return u.email.toLowerCase();}catch(e){if(e instanceof AppError)throw e;throw new AppError(401,'Tu sesión ha caducado. Vuelve a entrar.');}}
type Context={tx:Transaction;root:FirebaseFirestore.DocumentReference;members:Member[];me:Member;revision:number;written:boolean};
// All writes update the shared family document, so competing bookings retry
// against the latest reservations, including participant conflicts across cars.
async function family<T>(req:Request,fn:(c:Context)=>Promise<T>){const account=await email(req),{db}=services(),root=db.doc('families/default');return db.runTransaction(async tx=>{const snap=await tx.get(root);const members:Member[]=snap.exists?snap.data()!.members:['m1','m2','m3','m4'].map((id,i)=>({id,name:i===0?'Administrador':`Familiar ${i+1}`,email:i===0?process.env.FAMILY_ADMIN_EMAIL!.toLowerCase():null,admin:i===0?1:0}));const me=members.find(m=>m.email===account);if(!me)throw new AppError(403,'Tu correo no está incluido en la familia. Pide al administrador que lo añada.');const context={tx,root,members,me,revision:snap.data()?.revision??0,written:false};const result=await fn(context);if(!snap.exists&&!context.written)tx.set(root,{members,revision:1});return result;});}
export async function state(req:Request){return family(req,async c=>{const [rs,ev]=await Promise.all([c.tx.get(c.root.collection('reservations')),c.tx.get(c.root.collection('events').orderBy('at','desc').limit(200))]);return {me:c.me,members:c.members,reservations:rs.docs.map(d=>d.data() as Reservation).sort((a,b)=>a.start-b.start),events:ev.docs.map(d=>d.data()).filter(e=>c.me.admin||e.payload.creator===c.me.id||e.payload.participants.includes(c.me.id)||e.payload.previousParticipants?.includes(c.me.id)),serverTime:Date.now()};});}
export async function save(req:Request,editing:boolean){const input=await req.json();if(!validShape(input)||(input.override!==undefined&&typeof input.override!=='boolean')||(editing&&(typeof input.id!=='string'||!Number.isSafeInteger(input.version))))throw new AppError(400,'Revisa los datos de la reserva.');return family(req,async c=>{const rows=await c.tx.get(c.root.collection('reservations'));const all=rows.docs.map(d=>d.data() as Reservation),old=editing?all.find(r=>r.id===input.id):undefined;if(editing&&!old)throw new AppError(404,'La reserva ya no existe.');if(old&&!c.me.admin&&old.creator!==c.me.id)throw new AppError(403,'Solo puedes modificar tus propias reservas.');if(old&&old.version!==input.version)throw new AppError(409,'La reserva ha cambiado. Actualiza antes de editarla.');if(input.override&&!c.me.admin)throw new AppError(403,'Solo el administrador puede aplicar excepciones.');const now=Date.now(),issues=violations(input,all.filter(r=>r.id!==old?.id),c.members,now),override=!!input.override&&!!c.me.admin;if(issues.length&&!override)throw new AppError(409,issues.join(' '));const id=old?.id??crypto.randomUUID(),eventId=crypto.randomUUID();const r:Reservation={id,car:input.car,start:input.start,end:input.end,participants:input.participants,note:input.note,creator:old?.creator??c.me.id,override:override?1:0,version:(old?.version??0)+1,updated:now};c.tx.set(c.root.collection('reservations').doc(id),r);c.tx.set(c.root.collection('events').doc(eventId),{id:eventId,reservation:id,actor:c.me.id,action:old?'modified':'created',at:now,payload:{...r,previousParticipants:old?.participants??[],violations:issues}});c.written=true;c.tx.set(c.root,{members:c.members,revision:c.revision+1});return {ok:true,id};});}
export async function cancel(req:Request){const {id,version}=await req.json();if(typeof id!=='string'||!id||id.includes('/')||!Number.isSafeInteger(version))throw new AppError(400,'Revisa la reserva.');return family(req,async c=>{const ref=c.root.collection('reservations').doc(id),snap=await c.tx.get(ref),old=snap.data() as Reservation|undefined;if(!old)throw new AppError(404,'La reserva ya no existe.');if(!c.me.admin&&old.creator!==c.me.id)throw new AppError(403,'Solo puedes cancelar tus propias reservas.');if(old.version!==version)throw new AppError(409,'La reserva ha cambiado. Actualiza antes de cancelarla.');c.tx.delete(ref);const eventId=crypto.randomUUID();c.tx.set(c.root.collection('events').doc(eventId),{id:eventId,reservation:id,actor:c.me.id,action:'cancelled',at:Date.now(),payload:old});c.written=true;c.tx.set(c.root,{members:c.members,revision:c.revision+1});return {ok:true};});}
export async function updateMembers(req:Request){const {members}=await req.json();return family(req,async c=>{if(!c.me.admin)throw new AppError(403,'Solo el administrador puede gestionar la familia.');if(!Array.isArray(members)||members.length!==4)throw new AppError(400,'La familia debe tener cuatro personas.');const ids=new Set(),emails=new Set();const clean:Member[]=members.map(m=>{if(!m||!['m1','m2','m3','m4'].includes(m.id)||ids.has(m.id)||typeof m.name!=='string'||!m.name.trim()||m.name.length>50||typeof m.email!=='string'||m.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(m.email))throw new AppError(400,'Revisa los nombres y correos.');ids.add(m.id);const email=m.email.toLowerCase();if(email&&emails.has(email))throw new AppError(400,'Cada persona debe tener un correo distinto.');emails.add(email);if(m.id===c.me.id&&email!==c.me.email)throw new AppError(400,'Tu correo debe conservarse.');return {id:m.id,name:m.name.trim(),email:email||null,admin:c.members.find(x=>x.id===m.id)!.admin};});c.written=true;c.tx.set(c.root,{members:clean,revision:c.revision+1});return {ok:true};});}
export async function respond(fn:()=>Promise<unknown>){try{return Response.json(await fn(),{headers:{'Cache-Control':'no-store'}});}catch(e){return Response.json({error:e instanceof AppError?e.message:'No se ha podido completar la operación.'},{status:e instanceof AppError?e.status:e instanceof SyntaxError?400:503,headers:{'Cache-Control':'no-store'}});}}
